### ISSUE TITLE
Craft anvil doesn't work

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#611]
### Describe the bug

Trying to craft anvils for the quest but is progressing.
Tried to use `anvil:0` and `anvil:2` (default from /bpa material item) in variable, but none of these config works.

**(using latest version: 4.7.5)**

### How to reproduce

Create this quest:
```yml
  construir-bigorna:
    name: 'Necessidade'
    type: craft
    variable: anvil:2 # or anvil:0
    required-progress: 28
    points: 95
    item:
      material: anvil:0
      name: '&eNecessidade'
      lore:
        - '&7Construa {#61FAB3}%required_progress% &7bigornas.'
        - ''
        - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

Try to progressing crafting some anvils.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/faa54c55-9e9c-4764-94fb-de8d12134c1d)
![image](https://github.com/user-attachments/assets/eef85385-155b-4a2c-817b-440ffe0a75dd)
