### ISSUE TITLE
Craft decorated pot doesn't work

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#612]
### Describe the bug
> **Update: still not working with only decorated_pot in variable**

Trying to craft decorated pots for the quest but is progressing.
Tried to use `decorated_pot:0` and only `decorated_pot` in variable, but none of these config works.

**(using latest version: 4.7.5)**

### How to reproduce

Create this quest:
```yml
  construir-vaso:
    name: 'Artesão de cerâmica'
    type: craft
    variable: decorated_pot:0
    required-progress: 6
    points: 95
    item:
      material: decorated_pot:0
      name: '&eArtesão de cerâmica'
      lore:
        - '&7Construa {#61FAB3}%required_progress% &7vasos.'
        - ''
        - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```
Try to progressing crafting some decorated pots.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/c913b751-e632-4a04-8812-1f601ed76a23)
![image](https://github.com/user-attachments/assets/ffbed1ab-5123-4b95-a5b3-4685dc37b980)
