### ISSUE TITLE
Craft shulker doesn't work

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#613]
### Describe the bug

Trying to craft shulkers (basic shulker, no colored) for the quest but is progressing.
Tried to use shulker_box:0 and shulker_box:1 (default from /bpa material item) in variable, but none of these config works.

### How to reproduce

Create this quest:
```yml
  construir-shulker:
    name: 'Mochilinha'
    type: craft
    variable: shulker_box:1
    required-progress: 4
    points: 95
    item:
      material: shulker_box:0
      name: '&eMochilinha'
      lore:
        - '&7Construa {#61FAB3}%required_progress% &7shulkers.'
        - ''
        - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

Try to progressing crafting some shulkers.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/922953fb-52ef-4287-89e4-d078f09a3f5a)
![image](https://github.com/user-attachments/assets/f50d17b8-31ca-4c2d-a1df-d7047d57d35a)
