### ISSUE TITLE
Consume pufferfish is not progressing

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#614]
### Describe the bug

Trying to consume pufferfish but is not counting.
Other quests about consuming is working fine, pufferfish for some reason is not.
Tried to use `pufferfish:0` and `pufferfish:3` (default from /bpa material item) in variable, but none of these config works.

**(using latest version: 4.7.5)**

### How to reproduce

Create this quest:
```yml
  consumir-baiacu:
    name: 'Bochechão'
    type: consume
    variable: pufferfish:3 # or 0
    required-progress: 28
    points: 95
    item:
      material: pufferfish:0
      amount: 1
      name: '&eBochechão'
      lore:
        - '&7Coma {#61FAB3}%required_progress% &7baiacus.'
        - ''
        - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

Try to progressing eating some pufferfishes.
