### ISSUE TITLE
right-click type holding a item

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#629]
### Describe the bug

Is not possible to complete a quest that need to right-click holding an specific item.
See that quest below. (This was working before I updated plugin version and purpur 1.21.1 to 1.21.3)

### How to reproduce

```yml
  '12':
    name: Procurando Dzxcraft
    type: right-click
    variable:
      holding:
        item: spyglass # or spyglass:0
    required-progress: 1
    points: 95
    item:
      material: spyglass
      name: '&eProcurando Dzxcraft'
      lore:
      - '&7Use uma luneta {#61FAB3}%required_progress%x&7 vezes.'
      - ''
      - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

### Screenshots / Videos

https://github.com/user-attachments/assets/b6939851-3c1a-4ece-9083-c8b2efae8946

### Server Log

https://mclo.gs/u73Dg7Z
