### ISSUE TITLE
Earn exp with auto pickup plugin

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#630]
### Describe the bug

This is a compatibility bug, so I don't know if is possible to be fixed. Hope that can be fixed! 😄 

> Important: There **is no bug** without pickup plugins or the exp option disabled.

### How to reproduce

1. Use any AutoPickup plugin, [example](https://www.spigotmc.org/resources/autopickup-1-21-support.70157/). 
2. This plugin has to pickup experience from dead mobs as well.
3. Create a gain-experience quest type.
4. Farm exp by killing mobs. The exp will sent directly to your exp bar.
5. Notice that quest is not progressing.

```yml
  exp:
    name: Moedor
    type: gain-experience
    variable: none
    required-progress: 100000
    points: 95
    item:
      material: experience_bottle:0
      amount: 1
      name: '&eMoedor'
      lore:
      - '&7Ganhe {#61FAB3}%required_progress% &7de experiência.'
      - '&7Auto recolhimento de mobs pode afetar!'
      - ''
      - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

### Server Log

https://mclo.gs/u73Dg7Z
