### ISSUE TITLE
Add option to disable leaderboard system

### ISSUE THREAD

**Issue by bobhenl** [titanlabs-mc/battle-pass#636]
### Describe the bug

Hello, I'd like to note that there's prob high memory usage in Leaderboards of Battlepass? Like I tested on server alone, didn't open the GUI, and it consumed like 3GB of ram per 5 mins? Shouldn't it at least consume only on opening menu, or so? Or consume even less, if possible? By saving to mysql or so?

https://spark.lucko.me/1LVZoaOydP

![Image](https://github.com/user-attachments/assets/f756cf84-f805-478f-b132-a91434d7edc7)

My settings:
```yml
leaderboards:
  # Create leaderboard cache and update it every X minutes.
  # Recommended for servers with large amount of players - if disabled on these server, plugin can crash when opening leaderboard
  # Disable only on low memory servers
  use-cache: true
  # Refresh leaderboard cache every X minutes
  # Use placeholder %battlepass_top_time% to get time to refresh
  cache-refresh-minutes: 10
  # Name of player if plugin couldn't find that player in server's cache
  not-found-name: Error
```

### How to reproduce

1. Start server & join
2. Use `/spark profiler start --alloc --only-ticks-over 50 --thread *`
3. Use /spark profiler stop OR open
4. Check the usage
