### ISSUE TITLE
Negative points without points: setting

### ISSUE THREAD

**Issue by SirJben** [titanlabs-mc/battle-pass#649]
### Describe the bug

There's an issue with the settings where completing quests result in negative points (-1) by default when the `points:` setting is missing.

### How to reproduce

e.g. without the `points:` setting
```
quests:
  1: 
    type: fish
    name: 'Fisherman'
    required-progress: 10
    item:
      material: FISH
      name: '&6&lChallenge: &aFisherman'
      lore:
      - '&7You must fish 10 times' 
      - '&7to complete this quest.'
      - ''
      - "&eProgress: %progress_bar%"
      - ''
      - '&eRewards'
      - '&6» &7$5,000'
      - '&6» &75,000 Tokens'
    complete-commands: 
        - "eco give %player% 5000"
        - "tokens add %player% 5000" 
    actions-version: 2
```
with `points:` setting
```
  2: 
    name: Alchemist
    type: brew
    required-progress: 1
    points: 0
    item:
      material: BREWING_STAND
      amount: 1
      name: '&6&lChallenge: &aAlchemist'
      lore:
      - '&7Brew 1 potion to'
      - '&7complete this quest.'
      - ''
      - '&eProgress: %progress_bar%'
      - ''
      - '&eRewards'
      - '&6» &7$5,000'
      - '&6» &75,000 Tokens'

### Screenshots / Videos

_No response_

### Server Log

_No response_
